### ISSUE TITLE
Simplify Either data type to represent a simple disjoint union

### ISSUE THREAD

**Issue by gcanti** [Effect-TS/data#364]
Currently, there seems to be duplication of functionality between `Either` and `Effect` in the context of error handling. This redundancy not only may confuse users when deciding which data type to use but also poses an unnecessary burden on maintainers. To ensure codebase consistency, improve developer experience, and ease maintenance efforts, I propose simplifying the `Either` data type to represent **a simple disjoint union** (as used by some type classes).

As a result, certain APIs in `Effect` that rely on `Either`, such as `runSyncEither` and `runPromiseEither`, can be reevaluated for removal. Instead, we can encourage the use of APIs like `runSyncExit` and `runPromiseExit`, which encompass the desired functionality for running effects and handling results.

**Comment by mikearnaldi** [comment]
100% in favour of removing duplication. I would still keep Either as a subtype of effect just like we do for option because it enables smooth composition for the cases where you use an either to represent an error. Note that while it shouldn't be it's sole usage there are cases where either comes in handy for example using `Effect.either(effect)` in a generator to then branch over the two cases of typed error vs success letting any untyped error bubble up

**Comment by gcanti** [comment]
Closed by https://github.com/Effect-TS/data/pull/378
