### ISSUE TITLE
Documentation Request: Migration guide from fp-ts to effect-ts/data

### ISSUE THREAD

**Issue by jituanlin** [Effect-TS/data#420]
I am having difficulty understanding the differences between *fp-ts* and *effect-ts/data*.

It appears that *effect-ts/data* is a part of *fp-ts* without the *typeclass*.

Why doesn't *data* in *effect-ts/data* implement the "typeclass"?

Additionally, how can I convert `ReadonlyArray<Option<A>>` to `Option<ReadonlyArray<A>>` if `sequence` and `Traversable` are not implemented in *effect-ts/data*?

**Comment by mikearnaldi** [comment]
The reason we don't use typeclasses is because they are generally useless in the context of TS, yes you could implement traversal with Traversable+Applicative but it would be stack-unsafe, in fp-ts all those functions ended up with concrete and specialized implementations ignoring the derivation.

If you really love your typeclasses you can find them in `@effect/typeclass` in the https://github.com/Effect-TS/typeclass repo.

You can do the conversion above using `Option.all(arrayOfOptions)`

**Comment by mikearnaldi** [comment]
The public facing doc is aimed at beginners who don't know anything about fp, not sure putting fp-ts related material there would be of help to most, for sure will scare away many.

For fp-ts folks one good intro can be found by the project https://github.com/pigoz/effect-crashcourse
